---
title: "Aaron_Mapping"
author: "aaron till"
date: "7/31/2018"
output: github_document
---


```{r}

library(ggmap)

```

determing where to build bbox
```{r}
min(na.omit(tidy_data)$hh_add_lng)
min(na.omit(tidy_data)$hh_add_lat)
max(na.omit(tidy_data)$hh_add_lng)
max(na.omit(tidy_data)$hh_add_lat)

```

```{r}

bbox = c(-90.56, 30.03 ,-90.49 ,30.085)

LA_map <- get_map(bbox, zoom = 14, maptype = 'toner-lite')

ggmap(LA_map)

```

```{r}

ggmap(LA_map) +
  geom_point(data = filter(tidy_data, cancer_after == 1 | is.na(cancer_after)), aes(x = hh_add_lng, y = hh_add_lat, color = cancer_after)) +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), color = 'red', size = 3)



```



```{r}

tidy_data %>%
  group_by(zone) %>%
  summarise(max_dist = max(denka_dist), max_lat = max(hh_add_lat), min_lat = min(hh_add_lat), max_lng = max(hh_add_lng), min_lng = min(hh_add_lng))



```





```{r}

cancer_points_generous_rings <- ggmap(LA_map) +
  geom_point(data=filter(tidy_data, cancer == 0), aes(hh_add_lng, hh_add_lat), size = 0.5, fill = 'white', color = 'grey', shape = 21) +
  geom_point(data=filter(tidy_data, cancer  == 1), aes(hh_add_lng, hh_add_lat), size = 0.5, color = 'red') +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), shape = 4, size = 3)+
  #scale_color_gradient(low = 'grey', high = 'red') +
  guides(color = FALSE, alpha = FALSE) +
    geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21,size = 56)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1,shape = 21, size = 88)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21, size = 134) +
    geom_label(data = cancer_zone_data, aes(x = min_lng - min_lng/30000, y = 30.065, label = zone)) 

cancer_points_generous_rings


```



```{r}

cancer_points_restricted_rings <- ggmap(LA_map) +
  geom_point(data=filter(tidy_data, cancer_after == 0), aes(hh_add_lng, hh_add_lat), size = 0.5, fill = 'white', color = 'grey', shape = 21) +
  geom_point(data=filter(tidy_data, cancer_after  == 1), aes(hh_add_lng, hh_add_lat), size = 0.5, color = 'red') +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), shape = 4, size = 3)+
  #scale_color_gradient(low = 'grey', high = 'red') +
  guides(color = FALSE, alpha = FALSE) +
    geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21,size = 56)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1,shape = 21, size = 88)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21, size = 134) +
    geom_label(data = cancer_zone_data, aes(x = min_lng - min_lng/30000, y = 30.065, label = zone)) 

cancer_points_restricted_rings

```

```{r}
tidy_data %>% 
  filter(cancer == 1) %>%
  group_by(hh_add_lat, hh_add_lng, hh_id) %>% 
  summarise(cancer_count = n())%>%
  ungroup() %>%
  group_by(cancer_count) %>%
  summarise(households = n()) %>%
  ungroup() %>%
ggplot(aes(x= factor(cancer_count), y = households)) +
        geom_bar(stat = 'identity') +
        geom_label(aes(y = 30, label = households))



```

```{r removing all people who moved in after 2013}

cancer_points_restricted_rings2 <- ggmap(LA_map) +
  geom_point(data=filter(tidy_data, cancer_after == 0 & move_in_year <= 2013), aes(hh_add_lng, hh_add_lat), size = 0.5, fill = 'white', color = 'grey', shape = 21) +
  geom_point(data=filter(tidy_data, cancer_after  == 1 & move_in_year <= 2013), aes(hh_add_lng, hh_add_lat), size = 0.5, color = 'red') +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), shape = 4, size = 3)+
  #scale_color_gradient(low = 'grey', high = 'red') +
  guides(color = FALSE, alpha = FALSE) +
    geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21,size = 56)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1,shape = 21, size = 88)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21, size = 134) +
    geom_label(data = cancer_zone_data, aes(x = min_lng - min_lng/30000, y = 30.065, label = zone)) 

cancer_points_restricted_rings2

```


```{r removing smokers}

# had to make real_hh_smoking from smoking because hh_smoking was mostly NA values

cancer_points_smokeless_rings <- ggmap(LA_map) +
  geom_point(data=filter(tidy_data, cancer == 0), aes(hh_add_lng, hh_add_lat), size = 0.5, fill = 'white', color = 'grey', shape = 21) +
    geom_point(data=filter(tidy_data, cancer == 1 & real_hh_smoking > 0), aes(hh_add_lng, hh_add_lat), size = 0.5, color = 'black') +
  geom_point(data=filter(tidy_data, cancer  == 1 & real_hh_smoking == 0), aes(hh_add_lng, hh_add_lat), size = 0.5, color = 'red') +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), shape = 4, size = 3)+
  #scale_color_gradient(low = 'grey', high = 'red') +
  guides(color = FALSE, alpha = FALSE) +
    geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21,size = 56)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1,shape = 21, size = 88)+
  geom_point(data = tidy_data[0:1,], aes(denka_lng, denka_lat), alpha = 1, shape = 21, size = 134) +
    geom_label(data = cancer_zone_data, aes(x = min_lng - min_lng/30000, y = 30.065, label = zone)) 

cancer_points_smokeless_rings


```



```{r}
tidy_data %>% 
  group_by(zone) %>%
  summarise(cancer_after_proportion = sum(na.omit(cancer_after))/n(), cancer_proportion = sum(na.omit(cancer))/n(),  n(), n2 = n() - (sum(na.omit(cancer)) - sum(na.omit(cancer_after))))


tidy_data %>% 
  filter(move_in_year <= 1970) %>%
  group_by(zone) %>%
  summarise(cancer_after_proportion = sum(na.omit(cancer_after))/n(), cancer_proportion = sum(na.omit(cancer))/n(),  n(), n2 = n() - (sum(na.omit(cancer)) - sum(na.omit(cancer_after))))


tidy_data %>%
  mutate(binary_smoking = ifelse(real_hh_smoking > 0, 1, 0)) %>%
  group_by(cancer, binary_smoking) %>%
  summarise(n())

```


# Shading attempts

```{r geom_rectange attempt}

ggmap(LA_map) +
  geom_rectangle(data = filter(cancer_zone_data, zone == 1), aes(x = denka_lng, y = denka_lat, xmin = min_lng, xmax = max_lng, ymin = min_lat, ymax = max_lat, fill = cancer_proportion), alpha = 0.5)+
  scale_fill_gradient(low = 'blue', high = 'red', limits = c(0,0.06))




```

```{r polygon attemp}

ggmap(LA_map) +
  geom_polygon(data = filter(tidy_data, zone == 1), aes(x = hh_add_lng, y = hh_add_lat, group = zone))
  


```


```{r point manipulation attempt}

ggmap(LA_map) +
  geom_point(data = filter(cancer_zone_data, zone == 1), aes(denka_lng, denka_lat, color = cancer_proportion), alpha = 0.1, size = 41)+
  geom_point(data = filter(cancer_zone_data, zone == 2), aes(denka_lng, denka_lat, color = cancer_proportion), alpha = 0.1, size = 85)+
  geom_point(data = filter(cancer_zone_data, zone == 3), aes(denka_lng, denka_lat, color = cancer_proportion), alpha = 0.1, size = 150)+
  #geom_point(data=tidy_data, aes(hh_add_lng, hh_add_lat, color = zone), size = 0.25) +
  geom_point(data = tidy_data, aes(x = denka_lng, denka_lat), shape = 4, size = 3)+
  scale_color_gradient(low = 'blue', high = 'red', limits = c(0,0.05))


```