---
title: "Import_Tidying"
author: "aaron till"
date: "7/30/2018"
output: github_document
---
```{r}

library(tidyverse)


```




# Run Louisiana on louisiana data, geo data and imported LA merge first
```{r}

select_data <- LA_merge %>%
  select(record_id, demographics_timestamp,hh_id, zone,hh_add, hh_num, age, sex, resident, hh_years, contains('_c_yr'), -contains('vague'), -contains('notes'), denka_dist,denka_lat, denka_lng, hh_add_lng, hh_add_lat, denka_dist, hh_smoking, smoking, contains('death_c'))

```


```{r}

pre_tidy_data <- select_data 

#replacing cancer elements wijth zero and adding move in year variable
pre_tidy_data <- pre_tidy_data %>%
  mutate_at(c(11:31), funs(replace(., is.na(.), 0))) %>%
  mutate(move_in_year = ifelse(!is.na(hh_years), 2018 - hh_years, NA))

#converting to numeric
pre_tidy_data[11:37] <- lapply(pre_tidy_data[11:37], as.numeric)

```

```{r}

#gathering all types of cancer together
tidy_data <- pre_tidy_data %>%
  gather('cancer_type', 'cancer_year', 11:31) %>%
  mutate(cancer_type = ifelse(cancer_year == 0, NA, cancer_type)) %>% 
  group_by(record_id, demographics_timestamp,hh_id, zone,hh_add, hh_num, age, sex,move_in_year, resident, hh_years, denka_dist, denka_lat, denka_lng, hh_add_lat, hh_add_lng, hh_smoking, smoking, hh_death_c, hh_death_c_type, hh_death_c_sex, hh_death_c_age, hh_death_c_year) %>%
  summarise('cancer_year' = max(cancer_year), 'cancer_type'  = any(!is.na(cancer_type)))#), first(cancer_type), NA)) 
              #taking the most recent year an individual has contracted cancer
```

#adding wether cancer occured after move in

```{r}
tidy_data <- tidy_data %>%
  mutate(cancer_after = ifelse(is.na(move_in_year), NA , ifelse(cancer_year >= move_in_year,1, 0))) %>%
  mutate(cancer_after = ifelse(is.na(cancer_after) & cancer_year == 0, 0, cancer_after))

```

#adding all possible cancer folks (not just confirmed cancer after)
```{r}
tidy_data <- tidy_data %>%
  mutate(cancer = ifelse(cancer_after == 1 | is.na(cancer_after), 1, 0))


```



#extending zone1

```{r}

tidy_data <- tidy_data %>%
  ungroup() %>%
  mutate(zone = ifelse(zone == 2 & denka_dist < 1300, 1, zone)) #%>%
  #mutate(zone = ifelse(zone == 3 & denka_dist < 2100, 2, zone))


```


```{r}

tidy_data %>%
  group_by(zone) %>%
  summarise(n())


```
# for zone manipulations in mapping 
```{r}

cancer_zone_data <- tidy_data %>%
  group_by(zone, denka_lat, denka_lng) %>%
  summarise(cancer_after_proportion = sum(na.omit(cancer_after))/n(), cancer_proportion = sum(na.omit(cancer))/n(),  n(), max_lat = max(hh_add_lat), min_lat = min(hh_add_lat),max_lng = max(hh_add_lng), min_lng = min(hh_add_lng))
 
cancer_zone_data


```

# correcting smoking data
```{r}

tidy_data <- left_join(tidy_data, tidy_data %>%
  group_by(hh_add_lat, hh_add_lng) %>%
  summarise(real_hh_smoking = max(hh_smoking, smoking, na.rm = TRUE))%>%
  ungroup()%>%
  mutate(real_hh_smoking = (ifelse(is.na(real_hh_smoking), 0, real_hh_smoking))))


```



# cancer death manipulations IN PROGRESS

```{r}
grep('^|\\s[:alpha:]+;|$', unlist(LA_merge$hh_death_c_type), value = TRUE)

grep('^|\\s[:alpha:]+;|$', unlist(LA_merge$hh_death_c_age), value = TRUE)


#c_death_type <- LA_merge %>%
 # filter(hh_death_c == 1)  %>%
  #select(hh_death_c_type)

#c_death_age <- LA_merge %>%
  #filter(hh_death_c == 1)  %>%
  #select(hh_death_c_age)


#cbind(data.frame(str_split(c_death_type, ';', simplify = TRUE)), data.frame(str_split(c_death_age, ';', simplify = TRUE)))
  #mutate(type = str_extract(hh_death_c_type, '[:alpha:]\\s:\\s[:alpha:]'))

#LA_merge %>%  select(hh_death_c, hh_death_c_type, hh_death_c_age) %>%
 # filter(hh_death_c_type == 1), 

```

